version: "3.7"
services:

   db-utenti:
     image: postgres:latest
     environment:
       POSTGRES_USER: poi
       POSTGRES_PASSWORD: poi
       POSTGRES_DB: Piemonte
     volumes:
       - db-utenti
     ports:
       - "5433:5433"
         
   pgadmin:
        image: dpage/pgadmin4:4.23
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
            PGADMIN_DEFAULT_PASSWORD: password
            PGADMIN_LISTEN_PORT: 6060
        ports:
            - 6060:6060
        volumes:
            - pgadmin:/var/lib/pgadmin
        depends_on:
            - db-utenti
   
   servizio-utenti:
     image: utenti:0.0.1-SNAPSHOT
     container_name: servizio-utenti
     expose:
       - 9090
     ports:
       - 9090:9090
     volumes:
       - servizio-utenti:/usr/app/

   

volumes:
   db-utenti:
   pgadmin:
   servizio-utenti:
