spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: YOUR_CLIENT_ID
            clientSecret: YOUR_CLIENT_SECRET
            redirect-uri-template: http://replace_with_your_domain.com:30193/login/oauth2/code/google
            scope:
              - email
              - profile