spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 9252713990-stvnud7tt3acsvc6vetkk06k1a0ju0dg.apps.googleusercontent.com
            clientSecret: 5c8uGskTCkEIU5sxLIseNLov
            scope:
              - email
              - profile