spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: YOUR_CLIENT_ID
            clientSecret: YOUR_CLIENT_SECRET
            scope:
              - email
              - profile